"""Static PFD shapes stamped from spare glyph codes of native font 6.

Generated by tools/build_pfp_shape_tiles.py.  Do not edit by hand: run
the cockpit font builder and then the tile builder again.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ShapeTiles:
    """Text runs that stamp one static shape, plus any rectangle rows."""

    runs: tuple
    remainder: tuple


TILE_COUNT = 28

COMPASS_ROSE = ShapeTiles(
    runs=(
        (208, 390, 'abcdefghijklm'),
        (174, 419, 'nopgggggggggggqrs'),
        (157, 448, 'tugggggggggggggggvwx'),
    ),
    remainder=((158, 477, 323, 1), (158, 478, 325, 1), (157, 479, 326, 1)),
)

VERTICAL_SPEED_WEDGE = ShapeTiles(
    runs=(
        (566, 116, 'ggyz'),
        (566, 145, 'ggg!'),
        (566, 174, 'gggg'),
        (566, 203, 'gggg'),
        (566, 232, 'gggg'),
        (566, 261, 'gggg'),
        (566, 290, 'ggg"'),
    ),
    remainder=((566, 319, 51, 1), (566, 320, 50, 1), (566, 321, 49, 1), (566, 322, 48, 1), (566, 323, 47, 1), (566, 324, 46, 1), (566, 325, 45, 1), (566, 326, 44, 1), (566, 327, 43, 1), (566, 328, 42, 1), (566, 329, 41, 1), (566, 330, 40, 1), (566, 331, 39, 1), (566, 332, 38, 1), (566, 333, 37, 1), (566, 334, 36, 1), (566, 335, 35, 1)),
)
