"""Notched PFD right-strip shape stamped from native font slot 3.

Generated by tools/build_pfp_quad_font.py.  Do not edit by hand.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ShapeTiles:
    """Text runs for one static shape and its final partial rows."""

    runs: tuple
    remainder: tuple
    font_id: int


TILE_COUNT = 11
DEVIATION_DIAMOND_CHARACTER = 'y'
SPEED_RING_CHARACTER = 'z'
SPEED_TRIANGLE_CHARACTER = '~'
DEVIATION_DIAMOND_FONT_ID = 3

VERTICAL_SPEED_WEDGE = ShapeTiles(
    runs=(
        (566, 116, 'mmno'),
        (566, 145, 'mmmp'),
        (566, 174, 'qrmm'),
        (583, 203, 'smm'),
        (566, 232, 'tumm'),
        (566, 261, 'vmmm'),
        (566, 290, 'mmmw'),
    ),
    remainder=((566, 319, 51, 1), (566, 320, 50, 1), (566, 321, 49, 1), (566, 322, 48, 1), (566, 323, 47, 1), (566, 324, 46, 1), (566, 325, 45, 1), (566, 326, 44, 1), (566, 327, 43, 1), (566, 328, 42, 1), (566, 329, 41, 1), (566, 330, 40, 1), (566, 331, 39, 1), (566, 332, 38, 1), (566, 333, 37, 1), (566, 334, 36, 1), (566, 335, 35, 1)),
    font_id=3,
)
